---
# TODO:
# - Make roles from below tasks

### Set global variables
- name: "Set global vars"
  hosts: all
  tasks:
  - name: "Set token fact and teleport IP"
    set_fact:
      teleport_token: "teleport-{{ ansible_hostname }}"
      teleport_ip_address: "{% for host in groups['teleport_server'] %}{{ hostvars[host]['ansible_facts']['eth0']['ipv4']['address'] }}{% endfor %}"


### Server configuration
- name: "Setup server"
  hosts: teleport_server

  tasks:
  - name: "Include teleport server setup"
    include_tasks: teleport-server-setup.yml


### Create inventory from linux_hosts for vscode
- name: "Setup vscode clients inventory"
  hosts: localhost
  gather_facts: no

  vars:
    linux_hosts_count: "{{ groups['linux_hosts'] | length }}"

  tasks:
  - name: "Generate vscode dynamic inventory"
    include_tasks: linux_hosts_vscode.yml
    loop: "{{ groups['linux_hosts'] }}"


### Setup vscode
- name: "Setup vscode on clients"
  hosts: linux_hosts_vscode
  gather_facts: no

  tasks:
  - name: "Include vars"
    include_vars:
      file: vars.yml
      
  # Based on
  # https://www.digitalocean.com/community/tutorials/how-to-set-up-the-code-server-cloud-ide-platform-on-centos-7
  - name: "Include vscode setup playbook"
    include_tasks: vscode-setup.yml


### Clients configuration
- name: "Setup clients"
  hosts: linux_hosts
  serial: 2

  tasks:
  - name: "Set lab id fact"
    ansible.builtin.set_fact:
      teleport_lab_id: "{{ ansible_date_time.minute }}"

  - name: "Include client setup tasks"
    include_tasks: teleport-client-setup.yml
