---

- name: "Create app directory if it does not exist"
  ansible.builtin.file:
    path: "{{ vscode_app_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '0755'

# - name: "Create home directory if it does not exist"
#   ansible.builtin.file:
#     path: "{{ vscode_home_dir }}"
#     state: directory
#     owner: "{{ vscode_user }}"
#     group: "{{ vscode_user }}"
#     mode: '0755'

- name: "Download and unarchive vscode"
  ansible.builtin.unarchive:
    src: "https://github.com/coder/code-server/releases/download/v{{ vscode_release }}/code-server-{{ vscode_release }}-linux-amd64.tar.gz"
    dest: "{{ vscode_app_dir }}"
    owner: "root"
    group: "root"
    remote_src: yes

- name: "Create a symbolic link"
  ansible.builtin.file:
    src: "{{ vscode_app_dir }}/code-server-{{ vscode_release }}-linux-amd64/bin/code-server"
    dest: "/usr/bin/code-server"
    owner: root
    group: root
    state: link

- name: "Add template for code-server.service"
  ansible.builtin.template:
    src: code-server.service.j2
    dest: /lib/systemd/system/code-server.service
    owner: root
    group: root
    mode: '0644'

- name: "Just force systemd reload"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Start vscode-server"
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: code-server

- name: "Install nginx"
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: "Create ssl directory"
  ansible.builtin.file:
    path: "{{ vscode_ssl_key | dirname }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '0700'

# Quick and dirty self signed cert
- name: "Generate self-signed certificate"
  ansible.builtin.shell: "openssl req -x509 -newkey rsa:4096 -keyout {{ vscode_ssl_key }} -out {{ vscode_ssl_crt }} -sha256 -days 365 -nodes -subj '{{ vscode_ssl_sub }}'"

- name: "Generate dhparm.pem"
  ansible.builtin.shell: "openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"

- name: "Add template for ssl code-server in nginx"
  ansible.builtin.template:
    src: code-server.nginx.j2
    dest: "/etc/nginx/conf.d/code-server.conf"
    owner: root
    group: root
    mode: '0644'

- name: "Start nginx"
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: nginx